### ISSUE TITLE
css in js

### ISSUE THREAD

**Issue by elonehoo** [wip-elonehoo/.ideas#6]
I want to implement a `js in css` library that can write css in js and then maybe export a method similar to `c` and then

```js
import { c } from 'xxxxx'
c('button',{
  color: 'red'
})
```

can be generated

```css
.button{
  color: red
}
```
